fixed sidebar font styles and bullet points
SF-WDI-42/publify-debugging-lab pull request #8
Opened 2018-01-19 22:10 UTC by SherifIsmail01

I changed the class reference for the sidebar titles in the HTML file instead of changing the styles for individual title classes

2018-01-19 22:12 UTC, esthersweon commented on publify_core/app/assets/javascripts/publify.js
> +//= require sidebar
Is this necessary?

2018-01-19 22:12 UTC, esthersweon commented on publify_core/app/assets/javascripts/sidebar.js
> +  $('#archives').sortable();
What does this have to do with the styles?

2018-01-19 22:12 UTC, esthersweon commented on publify_core/app/assets/stylesheets/sidebar_admin.css.scss
> +.sidebar_title {
There is no HTML that has this class anymore.

2018-01-19 22:13 UTC, mnfmnfm commented on publify_core/app/assets/stylesheets/sidebar_admin.css.scss
> +.sidebar_title {
If you're changing the class in the view, why do you need this CSS?

2018-01-19 22:46 UTC, mnfmnfm requested changes

2018-01-19 22:46 UTC, mnfmnfm commented on publify_core/app/assets/javascripts/publify.js
> +//= require_self
Unnecessary change in this file

2018-01-19 22:46 UTC, mnfmnfm commented on publify_core/app/assets/stylesheets/sidebar_admin.css.scss
> +}
Unnecessary change in this file

2018-01-19 22:46 UTC, mnfmnfm commented on publify_core/app/views/archives_sidebar/_content.html.erb
> +
Unnecessary extra newline

2018-01-19 22:46 UTC, mnfmnfm commented on publify_core/app/views/archives_sidebar/_content.html.erb
> +<% end %>
Leaving a newline at the end of each file is considered best practice.

2018-01-22 02:07 UTC, mnfmnfm commented
You still have the problem of changing 3 files when only one has actual changes.

2025-02-25 15:50 UTC, closed without merging